T-10404855 nav bar and layout scalable refactoring fix
solovevayaroslavna/simbirgwent pull request #11
Opened 2023-05-23 08:22 UTC by B0gda

2023-05-23 08:52 UTC, solovevayaroslavna requested changes

2023-05-23 08:52 UTC, solovevayaroslavna commented on package.json
> +    "eslint-plugin-material-ui": "^1.0.1",
Зачем? Почему он добавился? Что будет если убрать?

2023-05-23 08:52 UTC, solovevayaroslavna commented on src/components/MainLayout/MainLayoutStyled.tsx
> +height: 100vh;
здесь не отработал eslint и prettier

2023-05-23 08:52 UTC, solovevayaroslavna commented on src/components/MainLayout/MainLayoutStyled.tsx
> +// display: flex;
все комменты надо почистить

2023-05-23 08:52 UTC, solovevayaroslavna commented on src/components/MainLayout/MainLayoutStyled.tsx
> +background: grey;
либо убрать серый цвет совсем, либо вынести в константы

2023-05-23 08:52 UTC, solovevayaroslavna commented on src/components/MainPage/CommonGameArea/CommonGameArea.styles.tsx
> +  // border-left: 0.001em solid ${colors.secondaryColor};
комментарии вернуть или убрать

2023-05-23 08:52 UTC, solovevayaroslavna commented on src/components/MainPage/CommonGameArea/CommonGameArea.tsx
> +      <CardsPanel />
переименуй нижнюю правую часть грида  на "Deck" либо "RestOfDeck" => колода/остаток колоды
![image](https://github.com/solovevayaroslavna/simbirgwent/assets/90199600/00746fc6-d005-4e08-9649-777f4a0cc4d7)

2023-05-23 08:52 UTC, solovevayaroslavna commented on src/components/MainPage/CommonGameArea/CommonGameArea.tsx
> +      <CardsPanel />
это будет лучше по смыслу

2023-05-23 08:52 UTC, solovevayaroslavna commented on src/components/MainPage/CommonGameArea/GameBoard/GameBoardPart/CardsRow.tsx
> +  // border: 0.001em solid ${colors.secondaryColor};
убрать или вернуть

2023-05-23 08:52 UTC, solovevayaroslavna commented on src/components/MainPage/CommonGameArea/UserCards/UserCardsWrapperStyled.tsx
> +// width: 20px;
аналогично (либо вернуть либо оставить)

2023-05-23 08:52 UTC, solovevayaroslavna commented on src/components/MainPage/MainPageStyled.tsx
> +aspect-ratio: 20 / 9;
сделать как в фигме 1170/720

2023-05-23 08:52 UTC, solovevayaroslavna commented on src/components/MainPage/MainPageStyled.tsx
> +max-height: 86%;
нужно на весь экран по высоте (ну или прям почти на весь)

2023-05-23 08:52 UTC, solovevayaroslavna commented on src/components/MainPage/ScorePanel/ScorePanelStyled.tsx
> +// border: 0.001em solid ${colors.secondaryColor};
вернуть или убрать

2023-05-25 06:37 UTC, B0gda commented on package.json
> +    "eslint-plugin-material-ui": "^1.0.1",
При запуске проекта, в отсутствии данной зависимости, ошибки не были обнаружены - предполагаю, что данная строка случайно перенеслась с более старой ветки.

2023-05-25 06:48 UTC, B0gda commented on src/components/MainLayout/MainLayoutStyled.tsx
> +background: grey;
цвет был убран, так как в будущем будет заменен на иллюстрацию

2023-05-25 06:52 UTC, B0gda commented on src/components/MainPage/CommonGameArea/CommonGameArea.styles.tsx
> +  // border-left: 0.001em solid ${colors.secondaryColor};
Строки границ не убирались - видимо произошла ошибка, но в итоге закомментированные строки были оставлены

2023-05-25 06:52 UTC, B0gda commented on src/components/MainPage/CommonGameArea/GameBoard/GameBoardPart/CardsRow.tsx
> +  // border: 0.001em solid ${colors.secondaryColor};
Строки границ не убирались - видимо произошла ошибка, но в итоге закомментированные строки были оставлены

2023-05-25 06:55 UTC, B0gda commented on src/components/MainPage/ScorePanel/ScorePanelStyled.tsx
> +// border: 0.001em solid ${colors.secondaryColor};
Строки границ не убирались - видимо произошла ошибка, но в итоге закомментированные строки были оставлены

2023-05-27 12:58 UTC, solovevayaroslavna commented
![image](https://github.com/solovevayaroslavna/simbirgwent/assets/90199600/ebc7db70-6884-45f0-a56e-5017e3db58de)
пожалуйста перепроверь пропорции в ширину

2023-05-27 13:03 UTC, solovevayaroslavna commented
такой же вопрос есть и к высоте, но этот момент мы будем переделывать в отдельной задаче т.к. ребята уже очень ждут влитие твоего PR

2023-06-01 09:45 UTC, solovevayaroslavna approved these changes

2023-06-01 09:48 UTC, merged