T 10685648 creating left layout
solovevayaroslavna/simbirgwent pull request #12
Opened 2023-05-25 15:49 UTC by dpodsobilov

2023-05-27 11:55 UTC, solovevayaroslavna requested changes

2023-05-27 11:55 UTC, solovevayaroslavna commented on src/components/App.tsx
> +function App() {
зачем тебе второй App.tsx внутри папки components? когда уже есть один файл app.tsx в корневике?

2023-05-27 11:55 UTC, solovevayaroslavna commented on src/components/MainPage/ScorePanel/ScorePanelStyled.tsx
> +    // align-items: center;
закомментированного кода не должно быть в PR если только он не представляет отдельной ценности в будущем
в таком случае следует отдельным комментарием прописать почему важно этот закомментированный код оставить

2023-05-27 12:20 UTC, dpodsobilov commented on src/components/App.tsx
> +function App() {
Действительно не нужен. Видимо случайно создал его

2023-05-27 12:20 UTC, dpodsobilov commented on src/components/MainPage/ScorePanel/ScorePanelStyled.tsx
> +    // align-items: center;
Хорошо, учту

2023-05-27 12:43 UTC, solovevayaroslavna requested changes

2023-05-27 12:43 UTC, solovevayaroslavna commented on src/components/MainPage/ScorePanel/ScorePanel.tsx
> +    <ScorePanelStyled>
нужно убратьбэкграунд изображение на всем layout
![image](https://github.com/solovevayaroslavna/simbirgwent/assets/90199600/a5d7abe7-8a50-4d6c-b3de-1ba0a6eaa75a)
![image](https://github.com/solovevayaroslavna/simbirgwent/assets/90199600/813af73c-d6ff-4f15-b0dc-875132dc931a)

2023-05-27 12:43 UTC, solovevayaroslavna commented on src/components/MainPage/ScorePanel/ScorePanel.tsx
> +    <ScorePanelStyled>
И давай с тобой немного все-таки переделаем( это моя ошибка, я не очень внимательно изначально посмотрела смысловые блоки игры - не стесняйтесь меня в этом поправлять если видите что можно сделать лучше чем это поставлено в задаче

Что предлагаю:

![image](https://github.com/solovevayaroslavna/simbirgwent/assets/90199600/1fa428ba-e6e0-460c-b67a-ee394d9ca067)

2023-05-27 12:43 UTC, solovevayaroslavna commented on src/components/MainPage/ScorePanel/ScorePanel.tsx
> +    <ScorePanelStyled>
в таком виде карточка игрока и противника станет одним компонентом

общее замечание - сделай на каждый контейнер отдельный компонент
прям по честному
папка с названием
внутри `index.tsx` файл и 
`export const something` из этого компонента
в самом же компоненте уже можешь положить <div> текст что это за компонент</div> и этому компоненту уже задать стили

у тебя получится что один и тот же компонент будет для 
![image](https://github.com/solovevayaroslavna/simbirgwent/assets/90199600/8b932c2e-f5cf-4ece-9583-35d0af72df48)

один и тот же компонент для 
![image](https://github.com/solovevayaroslavna/simbirgwent/assets/90199600/49a3f67c-831d-443e-8c8b-789804b51506)

2023-05-27 12:43 UTC, solovevayaroslavna commented on src/components/MainPage/ScorePanel/ScorePanel.tsx
> +    <ScorePanelStyled>
просто ты их в коде напишешь два раза
т.е. 
```
<Component1>
<Component2>
<CenterComponent>
<Component2>
<Component1>
```

2023-05-27 12:43 UTC, solovevayaroslavna commented on src/components/MainPage/ScorePanel/ScorePanel.tsx
> +    <ScorePanelStyled>
в дальнейшем при разработке этих компонентов все их отличия будут определяться проброшенными сверху пропсами

2023-05-27 12:55 UTC, solovevayaroslavna commented on src/components/MainPage/ScorePanel/ScorePanelStyled.tsx
> +    // align-items: center;
+если увидел ранее до тебя пропущенные на ревью комментарии или грязь в коде - хорошим тоном будет поинтересоваться у виновника такого можно ли их убрать и убрать их, если в процессе работы ты затрагиваешь это место

2023-05-27 13:32 UTC, solovevayaroslavna approved these changes, later dismissed

2023-06-01 12:12 UTC, dpodsobilov commented on src/components/MainPage/ScorePanel/ScorePanelStyled.tsx
> +    // border-right: 0.001em solid ${colors.secondaryColor};
Эти комментарии Богдан оставил

2023-06-09 06:53 UTC, solovevayaroslavna commented on src/components/MainPage/ScorePanel/ScorePanelStyled.tsx
> +    // border-right: 0.001em solid ${colors.secondaryColor};
прекрасный коммент =) но в таком случае должно быть два исхода
1) я пошел к коллеге, спросил могу ли я убрать комментарии, он сказал что это он оставил случайно и их можно убрать, я убираю
2) я пошел к коллеге, коллега говорит что комментарии нужные, я их не убираю и добавляю комментарий почему этот комментарий должен остаться и почему его нельзя убирать, какая в нем ценность для дальнейшей разработки

варианта: "тимлид спросил зачем комментарий, я ответил "это не мой" и на этом всё" в проактивном коллективе разработчиков быть не должно =)

2023-06-09 06:56 UTC, solovevayaroslavna commented on src/components/MainPage/ScorePanel/ScorePanelStyled.tsx
> +    // border-right: 0.001em solid ${colors.secondaryColor};
вообще привыкайте что нет позиции "это не моё, моя хата с краю, ничего не знаю"
если во время вашего ревью кто-то из разработчиков заметил некачественный код или грязь, не зависимо от того ваша она или нет - это проблема не Васи, не Пети, это проблема всей команды и всего проекта, и не должно быть позиции "это не мое, убирать не мне". Именно поэтому настоятельно рекомендую начинать учавствовать в ревью других PR, т.к. найдя ошибку у коллеги, потом не придётся исправлять её самому, если она найдется или заметится во время твоего ревью =)

2023-06-09 06:57 UTC, solovevayaroslavna commented on src/components/MainPage/ScorePanel/ScorePanelStyled.tsx
> +    // border-right: 0.001em solid ${colors.secondaryColor};
ревьюер тоже человек, он может что-то пропустить, поэтому в идеальном мире ревьюеров всегда несколько, то что пропустит один - другой заметит

2023-06-10 13:10 UTC, dpodsobilov commented on src/components/MainPage/ScorePanel/ScorePanelStyled.tsx
> +    // border-right: 0.001em solid ${colors.secondaryColor};
Понял)

2023-06-14 14:25 UTC, evnikitin approved these changes

2023-06-14 14:27 UTC, merged