creating types of props for PlayerCard, implementing player image
solovevayaroslavna/simbirgwent pull request #13
Opened 2023-05-28 09:55 UTC by dpodsobilov

2023-06-16 14:55 UTC, dpodsobilov commented on src/components/MainLayout/MainPage/ScorePanel/ScorePanel.tsx
Пока нет бэка, я прописал игроков для примера внутри этой компоненты, дальше они пробрасываются в PlayerCard.

2023-06-16 14:55 UTC, dpodsobilov commented on src/components/MainLayout/MainPage/ScorePanel/PlayerCard/PlayerImage/ShieldImage/ShieldImageStyled.tsx
Сделал отрицательное положение, потому что у картинок большой прозрачный фон.

2023-06-20 07:47 UTC, solovevayaroslavna requested changes

2023-06-20 07:47 UTC, solovevayaroslavna commented on .idea/inspectionProfiles/Project_Default.xml
файлы редактора не должны коммититься в общий код, они должны быть в git.ignore

2023-06-20 07:47 UTC, solovevayaroslavna commented on .idea/vcs.xml
не должно быть в коммите

2023-06-20 07:47 UTC, solovevayaroslavna commented on .idea/workspace.xml
не должно быть в коммите

2023-06-20 07:47 UTC, solovevayaroslavna commented on src/components/MainLayout/MainPage/ScorePanel/PlayerCard/PlayerDeckInfo/PlayerLifes/PlayerLifes.tsx
> +    bright1 = true;
из кода не совсем очевидно что за bright1 и bright2

2023-06-20 07:47 UTC, solovevayaroslavna commented on src/components/MainLayout/MainPage/ScorePanel/PlayerCard/PlayerDeckInfo/PlayerLifes/PlayerLifes.tsx
> +    bright1 = true;
![image](https://github.com/solovevayaroslavna/simbirgwent/assets/90199600/99c02a77-6e0e-4729-b22f-1565cb36a3c0)

2023-06-20 07:47 UTC, solovevayaroslavna commented on src/components/MainLayout/MainPage/ScorePanel/PlayerCard/PlayerDeckInfo/PlayerLifes/PlayerLifes.tsx
> +      <Life $bright={bright2} />
почему $? впервые вижу такую конструкцию

2023-06-20 07:47 UTC, solovevayaroslavna commented on src/components/MainLayout/MainPage/ScorePanel/PlayerCard/PlayerImage/PlayerImage.types.tsx
> +  northKingdoms = 'NORTH_KINGDOMS',
выше уже есть место где объявляется fraction
зачем второй раз? 
![image](https://github.com/solovevayaroslavna/simbirgwent/assets/90199600/9ee865c4-18b4-49ee-a4b5-1ed28963fa77)

2023-06-20 07:47 UTC, solovevayaroslavna commented on src/components/MainLayout/MainPage/ScorePanel/PlayerCard/PlayerInfo/PlayerInfo.tsx
> +) {
такое чувство что линтер тут не отработал

2023-06-20 07:47 UTC, solovevayaroslavna commented on src/components/MainLayout/MainPage/ScorePanel/ScorePanel.tsx
извиняюсь за душноту, но "внутри этоГО компонента", в проф.сообществе компоненты реакт принято называть в мужском роде

2023-06-20 07:47 UTC, solovevayaroslavna commented on src/components/MainLayout/MainPage/ScorePanel/ScorePanel.tsx
> +enum Fraction {
ещё один enum?
надо в одном месте написать и экспортировать в другие

2023-06-20 18:13 UTC, dpodsobilov commented on src/components/MainLayout/MainPage/ScorePanel/ScorePanel.tsx
Хорошо)

2023-06-20 19:07 UTC, dpodsobilov commented on .idea/inspectionProfiles/Project_Default.xml
Понял, всю папку .idea поместил в gitignore, убрал из отслеживаемых файлов

2023-06-20 19:07 UTC, dpodsobilov commented on .idea/vcs.xml
Всю папку .idea поместил в gitignore, убрал из отслеживаемых файлов

2023-06-20 19:07 UTC, dpodsobilov commented on .idea/workspace.xml
Всю папку .idea поместил в gitignore, убрал из отслеживаемых файлов

2023-06-20 19:09 UTC, dpodsobilov commented on src/components/MainLayout/MainPage/ScorePanel/PlayerCard/PlayerDeckInfo/PlayerLifes/PlayerLifes.tsx
> +    bright1 = true;
Переименовал в playerLifeOne и playerLifeTwo. В зависимости от их значения, у игрока отображается 0, 1 или 2 жизни

2023-06-20 19:10 UTC, dpodsobilov commented on src/components/MainLayout/MainPage/ScorePanel/PlayerCard/PlayerDeckInfo/PlayerLifes/PlayerLifes.tsx
> +      <Life $bright={bright2} />
Видимо немного сошел с ума :)
Исправил

2023-06-21 07:10 UTC, dpodsobilov commented on src/components/MainLayout/MainPage/ScorePanel/ScorePanel.tsx
> +enum Fraction {
Исправил: создал Player.types.tsx, разместил перечисления в нём и импортировал их в нужных компонентах.

2023-06-21 07:11 UTC, dpodsobilov commented on src/components/MainLayout/MainPage/ScorePanel/PlayerCard/PlayerInfo/PlayerInfo.tsx
> +) {
Исправлено

2023-06-21 07:11 UTC, dpodsobilov commented on src/components/MainLayout/MainPage/ScorePanel/PlayerCard/PlayerImage/PlayerImage.types.tsx
> +  northKingdoms = 'NORTH_KINGDOMS',
Исправил: создал Player.types.tsx, разместил перечисления в нём и импортировал их в нужных компонентах.

2023-06-27 14:25 UTC, solovevayaroslavna approved these changes

2023-06-27 14:27 UTC, merged