T 11017563 create minimized card
solovevayaroslavna/simbirgwent pull request #19
Opened 2023-06-23 11:29 UTC by evnikitin

The following changes have been made in this PR:
- added a minimized card instead of a common card;
- replaced the power indicator to allow for the option of adding images instead of text. This was necessary due to the use of special cards;
-  changed the styles of certain indicators and containers for the purpose of reusability.

2023-06-28 08:08 UTC, solovevayaroslavna requested changes

2023-06-28 08:08 UTC, solovevayaroslavna commented on src/components/MainLayout/MainPage/CommonGameArea/UserCards/UserCards.tsx
> +// import { Card } from '../../../../Shared/Card'; если нужно, то можно поставить карту с описанием
do we need this comment?

2023-06-28 08:08 UTC, solovevayaroslavna commented on src/components/Shared/Card/CardComponentsStyled.ts
> +  z-index:-1;
why we need -1?

2023-06-28 08:08 UTC, solovevayaroslavna commented on src/utils/Images.utils.ts
> +      power: one,
why power is string?
I don't think that BE will send to us something else besides numbers

2023-06-28 08:08 UTC, solovevayaroslavna commented on src/utils/Images.utils.ts
> +      power: snowflake,
the weather card is another type of card, so....
as example

type CardType: {
id: number/string,
power: number,
header: string,
text: string
}
type WeatherCard: {
id: ...
header:...
text:...
}

const arrayOfAllCards: Array<CardType|WeatherCard> = [ usualCard, weatherCard]

2023-06-28 08:08 UTC, solovevayaroslavna commented on src/utils/Images.utils.ts
> +      power: snowflake,
or you can use power?: number as unrequired field, but better to use different interfaces like

interface CommonCard = {
props, which we have in all type of cards
}

then 
interface ArmyCard extends CommonCard {
props for ArmyCard, which we haven't in common card
}

then interface WeatherCard extends CommonCard {
props for weather card, which we haven't in common card
}

2023-06-29 15:01 UTC, evnikitin commented on src/components/MainLayout/MainPage/CommonGameArea/UserCards/UserCards.tsx
> +// import { Card } from '../../../../Shared/Card'; если нужно, то можно поставить карту с описанием
not needed, will be removed

2023-06-29 15:21 UTC, evnikitin commented on src/components/Shared/Card/CardComponentsStyled.ts
> +  z-index:-1;
I use -1 to not set z-index values for all components, but only for the TypeOfArmyStyled component, which is always positioned behind other components.

2023-07-11 04:45 UTC, solovevayaroslavna commented on src/components/Shared/Card/CardComponentsStyled.ts
> +  z-index:-1;
https://techrocks.ru/2021/09/18/how-to-manage-z-index-in-css/ please read this article and create a function with jeneration of z indexes. just nubmer -1 is not a good practice

2023-07-11 04:52 UTC, solovevayaroslavna commented on src/utils/Images.utils.ts
> +      power: snowflake,
it is still incorrect
to incorrectly specify power in both types as the same field (or rather, it is technically possible and in some cases applicable, but in our case it is logically incorrect)

it is more correct to remove power as a property from the weather card and add type to weater card

as you can see i removed power in previous comment from weatherCard
![image](https://github.com/solovevayaroslavna/simbirgwent/assets/90199600/85ecd00f-a655-41d9-89fe-b0a7b60a2622)
so if we need to detect wich weather card we have it's usful to use type: snow, where snow is also enum of cards

2023-07-11 04:54 UTC, solovevayaroslavna commented on src/utils/Images.utils.ts
> +      power: snowflake,
but, to be honest it depends more from api, so i would suggest to leave it as it is and wait for api

2023-07-11 04:55 UTC, solovevayaroslavna commented on src/utils/Images.utils.ts
> +      power: snowflake,
so this thread we can leave as resolved

2023-07-11 10:12 UTC, evnikitin commented on src/components/Shared/Card/CardComponentsStyled.ts
> +  z-index:-1;
function has been added

2023-07-12 06:52 UTC, solovevayaroslavna approved these changes

2023-07-13 15:03 UTC, merged