T 9810878 create card
solovevayaroslavna/simbirgwent pull request #9
Opened 2023-05-04 06:21 UTC by evnikitin

2023-05-04 09:01 UTC, solovevayaroslavna commented on src/components/App.tsx
> +  const cards = createCards();
давай сразу чтобы в app бардак не наводить - отдельный компонент Test/Present как угодно называй и в него складывай все что нужно временное для карточек, как только появится место куда карточку физически можно прицепить мы её перенесем, но в App функции и верстку, не клади иначе будет много конфликтов. Максимум в апп - 1 компонент для всего связанного с карточкой, чисто чтобы можно было посмотреть

2023-05-04 09:01 UTC, solovevayaroslavna commented on src/components/Card/Card.tsx
> +export function Card(props) {
давай через типы и интерфейсы, проптайпс на проектах с TS не используют

2023-05-04 09:01 UTC, solovevayaroslavna commented on src/components/Card/Card.tsx
> +export function Card(props) {
да и в целом мало где сейчас проптайпсы встретишь
const CardProps = interface {
header: string,
image: string (скорее всего картинки будем брать из бд, но это не точно, я подумаю над этим вопросом)
text: string,
power: number
}

2023-05-04 09:01 UTC, solovevayaroslavna commented on src/utils/Images.utils.ts
> +    id: 1, amount: 4, ability: 1, power: 11, category: 1, header: 'Гребанная пехтура', text: 'Пожертвуйте грошик ветерану Бренны', image: `${hero1}`,
image: `${hero1}`, - давай так и оставим до момента пока бэкендеры бд не поднимут)

2023-05-04 09:01 UTC, solovevayaroslavna commented on package.json
> +    "prop-types": "^15.8.1",
они тут не нужны)

2023-05-04 09:01 UTC, solovevayaroslavna commented on src/components/Card/CardComponentsStyled.tsx
> +export const IndicatorStyled = styled.div<{ Mytop?: string }>`
почему переменная Mytop не по camelCase?

2023-05-19 08:07 UTC, solovevayaroslavna requested changes

2023-05-19 08:07 UTC, solovevayaroslavna commented on src/components/Card/Card.tsx
> +        position: 'relative', height: '100vh', width: '53vh', border: '2px bold grey', marginBottom: '5%',
1. стили надо через styled
2. 100vh -это конечно хорошо, но когда у тебя карточка будет 2жды на странице (пример прикрепляю) то тебе надо высоту карточки брать относительно контейнера, т.е. передать сверху какие-то пропорции, поэтому vh/vw тут не подойдут. Сделай на странице пример из 3х карточек. Каждую карточку оберни в родителя. А родителям задай разные размеры. одному например 100vh*53vh второму 50vh*26.5vh и т.д а карточка внутри этих родителей должна быть 100% по высоте и 100% по ширине родителя. т.е. размеры карточки полностью подстраиваются под родителя
![image](https://github.com/solovevayaroslavna/simbirgwent/assets/90199600/f05cdc83-7519-43d0-b5d9-ef567d4134c4)

2023-05-19 08:07 UTC, solovevayaroslavna commented on src/components/Card/Card.tsx
> +      <CartDescription header={header}>{text}</CartDescription>
carT => carD

2023-05-19 08:07 UTC, solovevayaroslavna commented on src/components/Card/Card.tsx
> +        <TypeOfArmy color="var(--color-type-something)" />
Всё что относится к левому индикатору лучше вынести в отдельный компонент с пропсами
![image](https://github.com/solovevayaroslavna/simbirgwent/assets/90199600/bf9dcd08-52ff-40bf-9ea0-779e5397e3eb)
+
1. давай всё-таки уберем svg (сделано хорошо, но в данном контексте нам нужно либо сделать прям красиво красиво - либо упростить) предлагаю упростить и оставить просто красный прямоугольник (под это подойдет лучше div), который заканчивается до mui paper, а текст подписей внизу вернуть на центр ('это будет проще)

2023-05-19 08:07 UTC, solovevayaroslavna commented on src/components/Card/Card.tsx
> +        <TypeOfArmy color="var(--color-type-something)" />
2. где рисовал, кстати svg?

2023-05-19 08:07 UTC, solovevayaroslavna commented on src/components/Card/Card.tsx
> +        <TypeOfArmy color="var(--color-type-something)" />
что за цвет? почему он не вынесен?

2023-05-19 08:07 UTC, solovevayaroslavna commented on src/components/Card/Card.tsx
> +        <IndicatorStyled myTop="45%">
почему понадобилось пробрасывать именно через props?

2023-05-19 08:07 UTC, solovevayaroslavna commented on src/components/Card/CardComponentsStyled.tsx
> +height: 15%;
к таким числам лучше оставлять коммент, почему 15*15 (через месяц два после начала разработки уже не очевидно почему тут так происходит)

2023-05-19 08:07 UTC, solovevayaroslavna commented on src/components/Card/CardComponentsStyled.tsx
> +border : .05em solid #000;
все цвета через переменные, даже #000

2023-05-19 08:07 UTC, solovevayaroslavna commented on src/components/Card/CardComponentsStyled.tsx
> +display:flex;
не отработал линтер

position: absolute; - есть пробел
display:flex; - нет пробела

2023-05-19 08:07 UTC, solovevayaroslavna commented on src/components/Card/CardComponentsStyled.tsx
> +font-size:calc(100vh/15);
тут надо подумать (не уверена что привязывать шрифт к vh - норм идея, поговорю ещё с коллегами)

2023-05-19 08:07 UTC, solovevayaroslavna commented on src/components/Card/CardComponentsStyled.tsx
> +export const TypeOfArmyStyled = styled.div<{ backgroundImage?: string }>`
зачем пробрасывать пропс если он не используется?

2023-05-19 08:07 UTC, solovevayaroslavna commented on src/components/Card/CardComponentsStyled.tsx
> +border : .05em solid #000;
все цвета должны быть константами

2023-05-19 08:07 UTC, solovevayaroslavna commented on src/components/Card/CardComponentsStyled.tsx
> +border : .05em solid #000;
лучше все бордеры делать одинаково
либо везде px либо везде em

2023-05-19 08:07 UTC, solovevayaroslavna commented on src/components/Card/CardDescription.tsx
> +  header:string,
проблемы с eslint, пробелы

2023-05-19 08:07 UTC, solovevayaroslavna commented on src/components/Card/CardDescription.tsx
> +function CartDescription({ header, children }: CartDescriptionProps) {
carT => carD

2023-05-19 10:10 UTC, evnikitin commented on src/components/Card/Card.tsx
> +        <TypeOfArmy color="var(--color-type-something)" />
Рисовал в Figma

2023-06-09 08:16 UTC, solovevayaroslavna commented on .vscode/launch.json
> +   // Для получения дополнительной информации посетите: https://go.microsoft.com/fwlink/?linkid=830387
это зачем? это vscd файлы (обычно все что касается редакторов должно быть добавлено по дефолту сразу в git ignore), так что убирай файл из PR, добавляй себе в git ignore

2023-06-09 08:16 UTC, solovevayaroslavna commented on src/components/Card/CardComponentsStyled.tsx
> +display: flex;
линтер не отработал, надо через линтер прогнать

2023-06-09 08:16 UTC, solovevayaroslavna commented on src/components/Card/CardComponentsStyled.tsx
> +width: calc(15*15%/8);т.к height/width = 15/8, то для того чтобы получить ширину, такую же как высоту, нужно умножить на 8/15`;
а комментарий?

2023-06-09 08:16 UTC, solovevayaroslavna commented on src/components/Card/CardComponentsStyled.tsx
> +width: 100%; //
коммент

2023-06-09 08:16 UTC, solovevayaroslavna commented on src/components/Card/CardComponentsStyled.tsx
> +border : .03em solid var(--color-black);
0.03em?

2023-06-09 08:16 UTC, solovevayaroslavna commented on src/components/Card/CardComponentsStyled.tsx
> +width: 100%; //
комментарий

2023-06-09 08:16 UTC, solovevayaroslavna commented on src/components/Card/CardComponentsStyled.tsx
> +width: calc(15*25%/8);
коммент лучше везде продублировать

2023-06-09 08:16 UTC, solovevayaroslavna commented on src/components/Card/CardDescription.tsx
> +    const parentDiv = divRef.current;
вообще в реальных проектах это лучше сделать с помощью темизации и глобального провайдера с привязкой к md,xl, s и т.д. размерам и media queries в одном конкретном месте (это в идеале, тут конечно в можно не заморачиваться так сильно)

2023-06-09 08:16 UTC, solovevayaroslavna commented on src/utils/Images.utils.ts
> +  cards.push({
а почему .push а не сразу написать в массив [{},{}....{}]

2023-06-13 09:54 UTC, solovevayaroslavna requested changes

2023-06-13 09:54 UTC, solovevayaroslavna commented on package.json
> +    "@types/prop-types": "^15.7.5",
надо убрать и попробовать без proptypes (если не нужны то убрать их из yaml)

2023-06-13 13:16 UTC, solovevayaroslavna approved these changes

2023-06-13 13:16 UTC, merged